<?xml version="1.0" encoding="utf-8"?><Database Name="wv90_Reporting" Class="LINQ_WellHeaderDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=OKCSQLPRD0794\INST4;Initial Catalog=wv90_Reporting;Integrated Security=True" SettingsObjectName="OpsView.My.MySettings" SettingsPropertyName="wv90_ReportingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.wvt_wvWellHeader" Member="wvt_wvWellHeaders">
    <Type Name="wvt_wvWellHeader">
      <Column Name="idwell" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="agent" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="area" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="basin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="basincode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="com" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="county" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="currentwellstatus1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="currentwellstatus2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="directionstowell" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="district" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="division" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dttmabandon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dttmfirstprod" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dttmrr" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dttmspud" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dttmwellclass" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dttmwelllic" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="elvcasflange" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="elvground" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="elvmudline" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="elvorigkb" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="elvtubhead" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="environmentsensitive" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ewdist" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ewflag" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="fieldcode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="fieldname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fieldoffice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="govauthority" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hih2s" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="hisitp" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="idrecelvhistory" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="idrecelvhistorytk" Type="System.String" DbType="VarChar(26)" CanBeNull="true" />
      <Column Name="idrecproblem" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="idrecproblemtk" Type="System.String" DbType="VarChar(26)" CanBeNull="true" />
      <Column Name="idrecsite" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="idrecsitetk" Type="System.String" DbType="VarChar(26)" CanBeNull="true" />
      <Column Name="latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="latlongdatum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="latlongsource" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lease" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="leasecode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="legalsurveyloc" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="legalsurveysubtyp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="legalsurveytyp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="locationnote" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="locationref" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="locationsensitive" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="locationtyp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nsdist" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="nsflag" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="operated" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="operator" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="operatorcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="platform" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="problemflag" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="riskclass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="slot" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stateprov" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="surfacerights" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="towndist" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="townflag" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="townname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="townstateprov" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="userboolean1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="userboolean2" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="userboolean3" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="userboolean4" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="userboolean5" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="userdttm1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="userdttm2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="userdttm3" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="userdttm4" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="userdttm5" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="usernum1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="usernum2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="usernum3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="usernum4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="usernum5" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="usertxt1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt10" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt4" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt5" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt6" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt7" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt8" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usertxt9" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="utmgridzone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="utmsource" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="utmx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="utmy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="waterdepth" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="wellclass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="wellconfig" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="wellida" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="wellidb" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="wellidc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="wellidd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="wellide" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="welllicensee" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="welllicenseno" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="wellname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="welltyp1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="welltyp2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="workingint" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="syslockmeui" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="syslockchildrenui" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="syslockme" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="syslockchildren" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="syslockdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sysmoddate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sysmoduser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="syscreatedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="syscreateuser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="systag" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="sysmoddatedb" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sysmoduserdb" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="syssecuritytyp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="syslockdatemaster" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>